app:
  distributed_storage_servers: 2
logger:
  level: 5
  output: stdout
metadb:
  host: metadb
  port: 5432
  db: db
  user: root
server:
  port: 8080
  upload_max_file_size_in_bytes: 10_000_000_000
  upload_max_metadata_in_bytes: 1_000
loader:
  upload_file_max_buffer_in_bytes: 10_000
  upload_large_file_max_buffer_in_bytes: 10_000_000