FROM golang:1.22.6

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY ./cmd ./cmd
COPY ./internal ./internal
COPY ./pkg ./pkg

RUN CGO_ENABLED=0 GOOS=linux go build -o ./storage ./cmd/storage/main.go

EXPOSE $STORAGE_EXPOSE_PORT

CMD ["./storage"]