FROM golang:1.22.6

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY ./cmd ./cmd
COPY ./internal ./internal
COPY ./pkg ./pkg
COPY ./config.yml ./config.yml

RUN CGO_ENABLED=0 GOOS=linux go build -o ./service ./cmd/service/main.go

EXPOSE 8080

CMD ["./service"]